#!/bin/sh

/opt/altera/altera12.1/quartus//linux/perl/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/ptf_update.pl snake_system.ptf 

/opt/altera/altera12.1/quartus//linux/perl/bin/perl -I$sopc_builder/bin -I$sopc_builder/bin/perl_lib -I$sopc_builder/bin/europa $sopc_builder/bin/mk_systembus.pl --sopc_directory=$sopc_builder --sopc_perl=/opt/altera/altera12.1/quartus//linux/perl --sopc_lib_path="/home/user4/spring13/mdk2133/Desktop/Snake_Plus+/opt/altera/altera12.1/quartus//../ip/altera/sopc_builder_ip+/opt/altera/altera12.1/quartus//../ip/altera/nios2_ip+/opt/altera/altera12.1/quartus//sopc_builder/components" --target_module_name=snake_system --system_directory=/home/user4/spring13/mdk2133/Desktop/Snake_Plus --system_name=snake_system --project_name=snakeplus.qpf --sopc_quartus_dir= $1
